firstwin.err.codes[2]: 创建成功
firstwin.err.codes[3]: 更新成功
firstwin.err.codes[4]: 删除成功
firstwin.err.codes[9999]: 未知错误
firstwin.err.codes[10002]: 通用参数错误
firstwin.err.codes[10003]: 没有找到合适的登陆处理方法
firstwin.err.codes[10004]: 令牌非法或者过期
firstwin.err.codes[10005]: 用户未被授权
firstwin.err.codes[20001]: 用户不存在
firstwin.err.codes[20004]: 获取用户wx openid失败
firstwin.err.codes[30001]: 分类不存在
firstwin.err.codes[40001]: 未找到首页优惠券活动
firstwin.err.codes[40004]: 未找到优惠券
firstwin.err.codes[40005]: 优惠券已过期
firstwin.err.codes[40006]: 您已经领取了这张优惠券
firstwin.err.codes[40008]: 优惠券不满足使用条件
firstwin.err.codes[40009]: 不支持的优惠券类型
firstwin.err.codes[40011]: 优惠券只存在可使用/已使用/已过期的情况
firstwin.err.codes[40012]: 优惠券核销失败
firstwin.err.codes[50002]: 订单中有已下架商品
firstwin.err.codes[50003]: 订单中有商品已售罄
firstwin.err.codes[50004]: 订单中有商品超出了购买上限
firstwin.err.codes[50005]: 订单金额与实际金额不匹配,可能某些商品价格有浮动
firstwin.err.codes[50006]: 用户没有这张优惠券
firstwin.err.codes[50008]: 订单优惠金额与实际优惠金额不匹配
firstwin.err.codes[50009]: 订单不存在
firstwin.err.codes[50010]: 订单已过期
firstwin.err.codes[50013]: 不支持该订单状态查询
